/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Devry Kawiryan
 */
public class Login extends javax.swing.JFrame {
private UserController control;

private boolean status;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        control =  new UserController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bungkus = new javax.swing.JPanel();
        BungkusLogin = new javax.swing.JPanel();
        LOGIN = new javax.swing.JLabel();
        BungkusInputLogin = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        BungkusButton = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lkregister = new javax.swing.JLabel();
        lkAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Bungkus.setBackground(new java.awt.Color(234, 234, 234));

        BungkusLogin.setBackground(new java.awt.Color(0, 153, 204));

        LOGIN.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("LOGIN");

        javax.swing.GroupLayout BungkusLoginLayout = new javax.swing.GroupLayout(BungkusLogin);
        BungkusLogin.setLayout(BungkusLoginLayout);
        BungkusLoginLayout.setHorizontalGroup(
            BungkusLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGIN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BungkusLoginLayout.setVerticalGroup(
            BungkusLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BungkusInputLogin.setBackground(new java.awt.Color(60, 60, 60));

        Username.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 204, 204));
        Username.setText("Username");

        Password.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setText("Password");

        username.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        BungkusButton.setBackground(new java.awt.Color(60, 60, 60));

        login.setBackground(new java.awt.Color(6, 104, 136));
        login.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BungkusButtonLayout = new javax.swing.GroupLayout(BungkusButton);
        BungkusButton.setLayout(BungkusButtonLayout);
        BungkusButtonLayout.setHorizontalGroup(
            BungkusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusButtonLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(login)
                .addGap(18, 18, 18)
                .addComponent(cancel)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        BungkusButtonLayout.setVerticalGroup(
            BungkusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(BungkusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(login))
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Belum punya akun daftar ");
        jLabel1.setToolTipText("");

        lkregister.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        lkregister.setForeground(new java.awt.Color(51, 204, 255));
        lkregister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lkregister.setText("disini");
        lkregister.setToolTipText("");
        lkregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lkregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lkregisterMouseClicked(evt);
            }
        });

        lkAdmin.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        lkAdmin.setForeground(new java.awt.Color(51, 204, 255));
        lkAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lkAdmin.setText("Admin");
        lkAdmin.setToolTipText("");
        lkAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lkAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lkAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BungkusInputLoginLayout = new javax.swing.GroupLayout(BungkusInputLogin);
        BungkusInputLogin.setLayout(BungkusInputLoginLayout);
        BungkusInputLoginLayout.setHorizontalGroup(
            BungkusInputLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BungkusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BungkusInputLoginLayout.createSequentialGroup()
                .addGroup(BungkusInputLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BungkusInputLoginLayout.createSequentialGroup()
                        .addGroup(BungkusInputLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BungkusInputLoginLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lkregister))
                            .addGroup(BungkusInputLoginLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(BungkusInputLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Username)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusInputLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lkAdmin)))
                .addContainerGap())
        );
        BungkusInputLoginLayout.setVerticalGroup(
            BungkusInputLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusInputLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lkAdmin)
                .addGap(22, 22, 22)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BungkusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(BungkusInputLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lkregister))
                .addContainerGap())
        );

        javax.swing.GroupLayout BungkusLayout = new javax.swing.GroupLayout(Bungkus);
        Bungkus.setLayout(BungkusLayout);
        BungkusLayout.setHorizontalGroup(
            BungkusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BungkusLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BungkusInputLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BungkusLayout.setVerticalGroup(
            BungkusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusLayout.createSequentialGroup()
                .addComponent(BungkusLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(BungkusInputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bungkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bungkus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String user = username.getText();
        String pass = password.getText();
        status = control.login(user, pass);
         JFrame parent = new JFrame();
        if (status) {
            JOptionPane.showMessageDialog(parent,"Selamat datang "+Public_Storage.username);
            Main form = new Main();
            form.setVisible(true);
            this.hide();
        }else{
            JOptionPane.showMessageDialog(parent, "Username atau password salah","Gagal Login",
    JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void lkregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lkregisterMouseClicked
        // TODO add your handling code here:
        Register form = new Register();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lkregisterMouseClicked

    private void lkAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lkAdminMouseClicked
        // TODO add your handling code here:
        AdminLogin form =  new AdminLogin();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_lkAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bungkus;
    private javax.swing.JPanel BungkusButton;
    private javax.swing.JPanel BungkusInputLogin;
    private javax.swing.JPanel BungkusLogin;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lkAdmin;
    private javax.swing.JLabel lkregister;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
