/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Devry Kawiryan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BungkusWelcome = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        BungkusMenuLuar = new javax.swing.JPanel();
        BungkusMenu = new javax.swing.JPanel();
        Pinjam = new javax.swing.JButton();
        Cari = new javax.swing.JButton();
        Kembalikan = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        BayarDenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        BungkusWelcome.setBackground(new java.awt.Color(0, 153, 204));

        Welcome.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(234, 234, 234));
        Welcome.setText("Welcome");

        javax.swing.GroupLayout BungkusWelcomeLayout = new javax.swing.GroupLayout(BungkusWelcome);
        BungkusWelcome.setLayout(BungkusWelcomeLayout);
        BungkusWelcomeLayout.setHorizontalGroup(
            BungkusWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusWelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Welcome)
                .addGap(22, 22, 22))
        );
        BungkusWelcomeLayout.setVerticalGroup(
            BungkusWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BungkusMenuLuar.setBackground(new java.awt.Color(60, 60, 60));

        BungkusMenu.setBackground(new java.awt.Color(60, 60, 60));
        BungkusMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        BungkusMenu.setForeground(new java.awt.Color(204, 204, 204));

        Pinjam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pinjam.setText("Pinjam");

        Cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        Kembalikan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kembalikan.setText("Kembalikan");
        Kembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalikanActionPerformed(evt);
            }
        });

        Profile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        BayarDenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BayarDenda.setText("Bayar Denda");
        BayarDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarDendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BungkusMenuLayout = new javax.swing.GroupLayout(BungkusMenu);
        BungkusMenu.setLayout(BungkusMenuLayout);
        BungkusMenuLayout.setHorizontalGroup(
            BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusMenuLayout.createSequentialGroup()
                .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BungkusMenuLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Kembalikan))
                    .addGroup(BungkusMenuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Profile)
                        .addGap(49, 49, 49)
                        .addComponent(BayarDenda)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        BungkusMenuLayout.setVerticalGroup(
            BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusMenuLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BayarDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BungkusMenuLuarLayout = new javax.swing.GroupLayout(BungkusMenuLuar);
        BungkusMenuLuar.setLayout(BungkusMenuLuarLayout);
        BungkusMenuLuarLayout.setHorizontalGroup(
            BungkusMenuLuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusMenuLuarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BungkusMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BungkusMenuLuarLayout.setVerticalGroup(
            BungkusMenuLuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusMenuLuarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BungkusMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BungkusWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BungkusMenuLuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BungkusWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BungkusMenuLuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void KembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KembalikanActionPerformed

    private void BayarDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarDendaActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarDenda;
    private javax.swing.JPanel BungkusMenu;
    private javax.swing.JPanel BungkusMenuLuar;
    private javax.swing.JPanel BungkusWelcome;
    private javax.swing.JButton Cari;
    private javax.swing.JButton Kembalikan;
    private javax.swing.JButton Pinjam;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel Welcome;
    // End of variables declaration//GEN-END:variables
}
