/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Devry Kawiryan
 */
public class Main extends javax.swing.JFrame {
    private UserController user;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        user = new UserController(this);
        user.GetProfile();
        user.GetRowProfile();
        System.out.println(Public_Storage.GetRowProfile);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BungkusWelcome = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        BungkusMenuLuar = new javax.swing.JPanel();
        BungkusMenu = new javax.swing.JPanel();
        Pinjam = new javax.swing.JButton();
        Cari = new javax.swing.JButton();
        Kembalikan = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        BungkusWelcome.setBackground(new java.awt.Color(0, 153, 204));

        Welcome.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(234, 234, 234));
        Welcome.setText("Welcome");

        javax.swing.GroupLayout BungkusWelcomeLayout = new javax.swing.GroupLayout(BungkusWelcome);
        BungkusWelcome.setLayout(BungkusWelcomeLayout);
        BungkusWelcomeLayout.setHorizontalGroup(
            BungkusWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BungkusWelcomeLayout.setVerticalGroup(
            BungkusWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BungkusMenuLuar.setBackground(new java.awt.Color(60, 60, 60));

        BungkusMenu.setBackground(new java.awt.Color(60, 60, 60));
        BungkusMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        BungkusMenu.setForeground(new java.awt.Color(204, 204, 204));

        Pinjam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pinjam.setText("Pinjam");
        Pinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinjamActionPerformed(evt);
            }
        });

        Cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cari.setText("Cari");
        Cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        Kembalikan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kembalikan.setText("Kembalikan");
        Kembalikan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalikanActionPerformed(evt);
            }
        });

        Profile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Profile.setText("Profile");
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-reading-50.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-book-shelf-50.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-borrow-book-50.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-return-book-50.png"))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Log Out");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-delete-64.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BungkusMenuLayout = new javax.swing.GroupLayout(BungkusMenu);
        BungkusMenu.setLayout(BungkusMenuLayout);
        BungkusMenuLayout.setHorizontalGroup(
            BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BungkusMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56))
                    .addGroup(BungkusMenuLayout.createSequentialGroup()
                        .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(BungkusMenuLayout.createSequentialGroup()
                                .addComponent(Profile)
                                .addGap(18, 18, 18)
                                .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Kembalikan)))
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        BungkusMenuLayout.setVerticalGroup(
            BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BungkusMenuLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(BungkusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout BungkusMenuLuarLayout = new javax.swing.GroupLayout(BungkusMenuLuar);
        BungkusMenuLuar.setLayout(BungkusMenuLuarLayout);
        BungkusMenuLuarLayout.setHorizontalGroup(
            BungkusMenuLuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusMenuLuarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BungkusMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BungkusMenuLuarLayout.setVerticalGroup(
            BungkusMenuLuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BungkusMenuLuarLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(BungkusMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BungkusWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BungkusMenuLuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BungkusWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BungkusMenuLuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        Profile form = new Profile();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ProfileActionPerformed

    private void KembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalikanActionPerformed
        // TODO add your handling code here:
        BookReturn form = new BookReturn();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_KembalikanActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        SearchBook form = new SearchBook();
        form.setVisible(true);
        this.hide();
    }//GEN-LAST:event_CariActionPerformed

    private void PinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinjamActionPerformed
        // TODO add your handling code here:
         JFrame parent = new JFrame();
        int row = Integer.parseInt(Public_Storage.GetRowProfile);
        if (row >0) {
            
        BookLoan form = new BookLoan();
        form.setVisible(true);
        this.hide();
       }else{
             JOptionPane.showMessageDialog(parent,"Hey "+Public_Storage.username+" Seleum Meminjam buku tolong lengkapi data diri dulu");
        }

    }//GEN-LAST:event_PinjamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Public_Storage.userid = "";
        Public_Storage.NamaLengkap = "";
        Public_Storage.GetRowProfile = "";
        Public_Storage.NoTlp = "";
        Public_Storage.Status = "";
        Public_Storage.username = "";
        Public_Storage.StatusBuku = "";


        Login form = new Login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BungkusMenu;
    private javax.swing.JPanel BungkusMenuLuar;
    private javax.swing.JPanel BungkusWelcome;
    private javax.swing.JButton Cari;
    private javax.swing.JButton Kembalikan;
    private javax.swing.JButton Pinjam;
    private javax.swing.JButton Profile;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
